name: Api

on:
  push:
    branches: [main]
    paths:
      - 'packages/api/**'

jobs:
  test:
    name: Tests
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0

      - uses: actions/setup-node@v3
        with:
          node-version: '15'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm server test
        env: 
          JWT_SECRET: adsofo2bodsf
          DATABASE_URL: file:./test.db


